language: python
python:
    - 2.7
    - 3.3
    - 3.4
    - 3.5

matrix:
  allow_failures:
      - python: 3.3
      - python: 3.4
      - python: 3.5

addons:
  apt:
    packages:
      - cython
install:
    - pip install -e .[testing]

script:
    - py.test
