---
name: esgf-pyclient
channels:
  - conda-forge
  - nodefaults

dependencies:
  # installation
  - pip
  - python >=3.9
  - requests
  - requests_cache
  - jinja2
  - defusedxml
  - webob >=1.8.9  # Python 3.13 support
  - myproxyclient >=2.1.1
  # testing
  - flake8
  - pytest
  # documentation
  - sphinx
  - nbsphinx
  - pandoc
  # ipython notebook
  - ipykernel
  - nbconvert
  - nbval
