# conda env create -f environment.yml
---
name: esgf-pyclient
channels:
  - conda-forge
  - nodefaults

dependencies:
  - pip
  - python>=3.7
  - requests
  - requests_cache
  - jinja2
  - defusedxml
  - webob
  - myproxyclient >=2.1.1
