---
name: esgf-pyclient
channels:
  - conda-forge
  - nodefaults

dependencies:
  # installation
  - pip
  - python>=3.8
  - requests
  - requests_cache
  - jinja2
  - defusedxml
  - webob
  - myproxyclient >=2.1.1
  # testing
  - flake8
  - pytest
  # documentation
  - sphinx
  - nbsphinx
  - pandoc
  # ipython notebook
  - ipykernel
  - nbconvert
  - nbval
