# conda env create -f environment.yml
name: esgf-pyclient
channels:
  - conda-forge
dependencies:
  - pip
  - python>=3.6
  - requests
  - requests_cache
  - jinja2
  - defusedxml
  - webob
  - myproxyclient
